name: android

on:
  release:
    types: [prereleased, released, published]
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main
      - feature/*
  push:
    branches:
      - main
      - feature/*
  schedule:
    # GMT timezone.
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

jobs:
  android-arm64:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-arm64
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk
  android-x86:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-x86
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk
  android-arm:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-arm
      nightly: ${{ github.event.inputs.nightly }}
      keep_artifacts: cobalt.apk

  final_android_job:
    runs-on: ubuntu-latest
    needs: [ android-arm, android-arm64]
    steps:
      - name: Final collections
        run: echo ${{ needs.android-arm.outputs.first_output }}
      - name: Download the gold arm thing
        uses: actions/download-artifact@v3
        with:
          name: buildoutput-android-arm-gold
          path: android-arm-gold
      - name: Download the qa arm thing
        uses: actions/download-artifact@v3
        with:
          name: buildoutput-android-arm-qa
          path: anrdoid-arm-qa
      - name: Download the gold arm64 thing
        uses: actions/download-artifact@v3
        with:
          name: buildoutput-android-arm64-gold
          path: android-arm64-gold
      - name: Download the qa arm64 thing
        uses: actions/download-artifact@v3
        with:
          name: buildoutput-android-arm64-gold
          path: android-arm64-qa
      - name: Download the gold x86 thing
        uses: actions/download-artifact@v3
        with:
          name: buildoutput-android-x86-gold
          path: android-x86-gold
      - name: Download the qa x86 thing
        uses: actions/download-artifact@v3
        with:
          name: buildoutput-android-x86-gold
          path: android-x86-qa
      - name: Doublecheck if all is there
        run: find . -type f
      - name: 'Upload Adnroid APKs'
        uses: actions/upload-artifact@c7d193f32edcb7bfad88892161225aeda64e9392 # v4
        if: inputs.keep_artifacts
        with:
          name: Android APKs
          path: ./*
          retention-days: 90
          compression-level: 0 # We expect kept artifacts to be already compressed
          if-no-files-found: error
